Allow HEAD request without body
emartech/koa-escher-auth pull request #27
Opened 2021-01-07 15:36 UTC by ggPeti

HEAD requests are supposed to work the same as GET according to [RFC-7231](https://tools.ietf.org/html/rfc7231#section-4.3.2).

2021-01-07 16:27 UTC, szenti approved these changes
LGTM

2021-01-07 16:28 UTC, szenti requested changes
Can you please provide a unit test for it? Thank you.

2021-01-07 17:23 UTC, szenti approved these changes
LGTM.

2021-01-07 20:24 UTC, merged

2021-01-12 14:39 UTC, bankyadam reviewed
LGTM also

2021-01-12 14:56 UTC, emarsys-deployer commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/koa-escher-auth/v/3.3.0)
- [GitHub release](https://github.com/emartech/koa-escher-auth/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: